/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/plants': {
        /** List plants for authenticated user */
        get: operations['listPlants'];
        /** Create a plant */
        post: operations['createPlant'];
    };
    '/plants/{id}': {
        /** Get a plant by ID */
        get: operations['getPlant'];
        /** Delete a plant */
        delete: operations['deletePlant'];
        /** Update a plant */
        patch: operations['updatePlant'];
        parameters: {
            path: {
                id: string;
            };
        };
    };
}

export type webhooks = Record<string, never>;

export interface components {
    schemas: {
        Plant: {
            id: string;
            userId: string;
            /** @example Monstera Deliciosa */
            name: string;
            photoUrl?: string | null;
            /** @example living-room */
            location: string;
            /** @example 7 */
            wateringDays: number;
            remindersEnabled: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreatePlantRequest: {
            name: string;
            photoUrl?: string | null;
            location: string;
            /** @default 7 */
            wateringDays?: number;
            /** @default false */
            remindersEnabled?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
    /** List plants for authenticated user */
    listPlants: {
        responses: {
            /** @description Array of plants */
            200: {
                content: {
                    'application/json': {
                        plants?: components['schemas']['Plant'][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                content: never;
            };
        };
    };
    /** Create a plant */
    createPlant: {
        requestBody: {
            content: {
                'application/json': components['schemas']['CreatePlantRequest'];
            };
        };
        responses: {
            /** @description Plant created */
            201: {
                content: {
                    'application/json': {
                        plant?: components['schemas']['Plant'];
                    };
                };
            };
            /** @description Missing required fields */
            400: {
                content: never;
            };
            /** @description Unauthorized */
            401: {
                content: never;
            };
        };
    };
    /** Get a plant by ID */
    getPlant: {
        parameters: {
            path: {
                id: string;
            };
        };
        responses: {
            /** @description Plant */
            200: {
                content: {
                    'application/json': {
                        plant?: components['schemas']['Plant'];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                content: never;
            };
            /** @description Not found */
            404: {
                content: never;
            };
        };
    };
    /** Delete a plant */
    deletePlant: {
        parameters: {
            path: {
                id: string;
            };
        };
        responses: {
            /** @description Deleted */
            204: {
                content: never;
            };
            /** @description Unauthorized */
            401: {
                content: never;
            };
            /** @description Not found */
            404: {
                content: never;
            };
        };
    };
    /** Update a plant */
    updatePlant: {
        parameters: {
            path: {
                id: string;
            };
        };
        requestBody?: {
            content: {
                'application/json': components['schemas']['CreatePlantRequest'];
            };
        };
        responses: {
            /** @description Updated plant */
            200: {
                content: {
                    'application/json': {
                        plant?: components['schemas']['Plant'];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                content: never;
            };
            /** @description Not found */
            404: {
                content: never;
            };
        };
    };
}
