/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/plants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List plants for authenticated user */
        get: operations["listPlants"];
        put?: never;
        /** Create a plant */
        post: operations["createPlant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a plant by ID */
        get: operations["getPlant"];
        put?: never;
        post?: never;
        /** Delete a plant */
        delete: operations["deletePlant"];
        options?: never;
        head?: never;
        /** Update a plant */
        patch: operations["updatePlant"];
        trace?: never;
    };
    "/plants/{id}/care-logs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log a care action for a plant */
        post: operations["logCareAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plants/{id}/care-logs/{logId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                logId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Undo a care action */
        delete: operations["undoCareAction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Plant: {
            id?: string;
            userId?: string;
            /** @example Monstera Deliciosa */
            name?: string;
            photoUrl?: string | null;
            /** @example living-room */
            location?: string;
            /** @example 7 */
            wateringDays?: number;
            waterAmountMl?: number | null;
            fertilizeDays?: number | null;
            repotDays?: number | null;
            remindersEnabled?: boolean;
            /** Format: date-time */
            lastWateredAt?: string | null;
            /** Format: date-time */
            lastFertilizedAt?: string | null;
            /** Format: date-time */
            lastRepottedAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreatePlantRequest: {
            name: string;
            photoUrl?: string | null;
            location: string;
            /** @default 7 */
            wateringDays: number;
            waterAmountMl?: number | null;
            fertilizeDays?: number | null;
            repotDays?: number | null;
            /** @default false */
            remindersEnabled: boolean;
        };
        UpdatePlantRequest: {
            name?: string;
            photoUrl?: string | null;
            location?: string;
            wateringDays?: number;
            waterAmountMl?: number | null;
            fertilizeDays?: number | null;
            repotDays?: number | null;
            remindersEnabled?: boolean;
        };
        PlantCareLog: {
            id: string;
            plantId: string;
            userId: string;
            /** @enum {string} */
            type: "WATER" | "FERTILIZE" | "REPOT";
            /** Format: date-time */
            doneAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        LogCareActionRequest: {
            /** @enum {string} */
            type: "WATER" | "FERTILIZE" | "REPOT";
            /** Format: date-time */
            doneAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listPlants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of plants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        plants?: components["schemas"]["Plant"][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createPlant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlantRequest"];
            };
        };
        responses: {
            /** @description Plant created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        plant?: components["schemas"]["Plant"];
                    };
                };
            };
            /** @description Missing required fields */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPlant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        plant?: components["schemas"]["Plant"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deletePlant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updatePlant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdatePlantRequest"];
            };
        };
        responses: {
            /** @description Updated plant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logCareAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogCareActionRequest"];
            };
        };
        responses: {
            /** @description Care log created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        log?: components["schemas"]["PlantCareLog"];
                        plant?: components["schemas"]["Plant"];
                    };
                };
            };
            /** @description Invalid care type */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Plant not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    undoCareAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                logId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Log deleted and plant reverted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        plant?: components["schemas"]["Plant"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Log not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
